grep

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -31,22 +31,22 @@ jobs:
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --max-complexity=10 --max-line-length=127
-        #FLAKE8_OUT=$(flake8 . --exit-zero --max-complexity=10 --max-line-length=127)
-        #echo "$FLAKE8_OUT"
+        #flake8 . --max-complexity=10 --max-line-length=127
+        FLAKE8_OUT=$(flake8 . --exit-zero --max-complexity=10 --max-line-length=127)
+        echo "$FLAKE8_OUT" | grep "^.*:[0-9]+:[0-9]+: E"
 
-        DIFF_EXISTS="false"
-        for f in $DIFF_FILES; do
-          FLAKE8_LINE=$(echo "$FLAKE8_OUT" | grep -F $f)
-          if [ -n "$FLAKE8_LINE" ]; then
-            echo "$FLAKE8_LINE"
-            DIFF_EXISTS="true"
-          fi
-        done
+        #DIFF_EXISTS="false"
+        #for f in $DIFF_FILES; do
+        #  FLAKE8_LINE=$(echo "$FLAKE8_OUT" | grep -F $f)
+        #  if [ -n "$FLAKE8_LINE" ]; then
+        #    echo "$FLAKE8_LINE"
+        #    DIFF_EXISTS="true"
+        #  fi
+        #done
 
-        if [ "$DIFF_EXISTS" = "true" ]; then
-          echo "::error::!!flake8 errors detected!!"
-          echo "::warning::My warning message"
-          echo "::debug::My debug message"
-          exit 1
-        fi
+        #if [ "$DIFF_EXISTS" = "true" ]; then
+        #  echo "::error::!!flake8 errors detected!!"
+        #  echo "::warning::My warning message"
+        #  echo "::debug::My debug message"
+        #  exit 1
+        #fi
